apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: eventinghello-ping-source
spec:
  schedule: "*/2 * * * *"
  jsonData: '{"message": "Welcome to Lenovo Serverless Lab3.1"}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventinghello
