apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: event-greeter-ping-source
spec:
  schedule: "*/2 * * * *"
  jsonData: '{"message": "Welcome to Lenovo Serverless Lab3.2!"}'
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1beta1
      kind: Channel
      name: eventinghello-ch
